base_url = "https://ezralazar.ca"
generate_feed = true
title = "Ezra's Site"
description = ""
author = "Ezra Lazar"
default_language = "en_CA"

[markdown]
highlight_code = true
highlight_theme = "dracula"

[extra]
# Put all your custom variables here
