base_url = "https://example.com"
generate_feed = true
title = "Ezra's Site"
description = ""

[markdown]
highlight_code = true
highlight_theme = "dracula"

[extra]
# Put all your custom variables here
